import tweepy
import random
import time


# === Your Twitter/X API Keys (v1.1) ===
consumer_key = "tpeXA5YY9Fzx4eHo3zbpwuEHI"
consumer_secret = "QkVfYtq4zihADIlifuSboCfJIHHnO5MINp3dsK6lEJxXTtUgUp"
access_token = "1363913360413233155-aQBXUmp0rOCGIa8sZlde4996HXKPXM"
access_token_secret = "06ZvXUN3a0hCetYbJSVdnx6O3SNF364jCE8ALVWa2Vk43"

# === Authenticate ===
# auth = tweepy.OAuth1UserHandler(consumer_key, consumer_secret, access_token, access_token_secret)
# api = tweepy.API(auth)  
client = tweepy.Client(
    consumer_key=consumer_key,
    consumer_secret=consumer_secret,
    access_token=access_token,
    access_token_secret=access_token_secret
)


# === Your Lyrics List ===
lyrics = [
   "you're insecure",
    "you're insecure, don't know what for",
    "you're turning heads when you walk through the door",
    "don't need makeup to cover up, being the way that you are is enough",
    "everyone else in the room can see it, everyone else, but you, ooh",
    "baby, you light up my world like nobody else",
    "the way that you flip your hair gets me overwhelmed",
    "but when you smile at the ground, it ain't hard to tell",
    "you don't know, oh-oh, you don't know you're beautiful",
    "you don't know, oh-oh, you don't know you're beautiful",
    "if only you saw what i can see, you'll understand why i want you so desperately",
    "right now i'm lookin' at you, and i can't believe",
    "that's what makes you beautiful",
    "so c-come on, you got it wrong, to prove i'm right, i put it in a song",
    "to prove i'm right, i put it in a song",
    "i don't know why you're being shy, and turn away when i look into your eyes",
    "na-na-na, na-na-na, na, na, na, na-na-na, na-na-na",
    "girl i see it in your eyes you're disappointed",
    "'cause i'm the foolish one that you anointed with your heart, i tore it apart",
    "and girl what a mess i made upon your innocence, and no woman in the world deserves this",
    "but here i am asking you for one more chance",
    "can we fall, one more time? stop the tape and rewind",
    "oh and if you walk away i know i'll fade 'cause there is nobody else",
    "it's gotta be you, only you",
    "now girl i hear it in your voice and how it trembles",
    "when you speak to me i don't resemble, who i was",
    "you've almost had enough, and your actions speak louder than words",
    "and you're about to break from all you've heard, don't be scared, i ain't going no where",
    "i'll be here, by your side",
    "no more fears, no more crying",
    "but if you walk away, i know i'll fade",
    "oh girl, can we try one more, one more time?",
    "one more, one more, can we try?",
    "can we try one more time to make it all better?",
    "i've tried playin' it cool, but when i'm lookin' at you",
    "i can't ever be brave, 'cause you make my heart race",
    "shot me out of the sky, you're my kryptonite",
    "you keep making me weak, yeah, frozen and can't breathe",
    "something's gotta give now, 'cause i'm dying just to make you see",
    "that i need you here with me now,'cause you've got that one thing",
    "'cause you've got that one thing",
    "so, get out, get out, get out of my head, and fall into my arms instead",
    "i don't, i don't, don't know what it is, but i need that one thing",
    "i need that one thing, and you've got that one thing",
    "now i'm climbing the walls, but you don't notice at all",
    "that i'm going out of my mind, all day and all night",
    "something's gotta give now, 'cause i'm dying just to know your name",
    "and i need you here with me now, 'cause you've got that one thing",
    "woah-oh-oh-oh, oh-ooh, oh-oh-oh-oh",
    "i'm broken, do you hear me?",
    "i'm blinded, 'cause you are everything i see",
    "i'm dancing alone",
    "i'm praying that your heart will just turn around",
    "and as I walk up to your door, my head turns to face the floor",
    "'cause i can't look you in the eyes and say",
    "when he opens his arms and holds you close tonight, it just won't feel right",
    "'cause i can love you more than this, yeah",
    "when he lays you down, i might just die inside",
    "it just don't feel right, 'cause I can love you more than this",
    "if i'm louder, would you see me?",
    "would you lay down in my arms and rescue me?",
    "'cause we are the same, you save me",
    "but when you leave, it's gone again",
    "and then i see you on the street, in his arms, i get weak",
    "my body fails, i'm on my knees, praying",
    "yeah, I've never had the words to say, but now i'm asking you to stay",
    "for a little while inside my arms, and as you close your eyes tonight",
    "i pray that you will see the light, that's shining from the stars, above",
    "it feels like we've been living in fast forward, another moment passing by (up, up, up all night)",
    "the party's ending but it's now or never, nobody's going home tonight (up, up, up all night)",
    "katy perry's on replay, she's on replay",
    "dj got the floor to shake, the floor to shake",
    "people going all the way, yeah, all the way",
    "i'm still wide awake",
    "i wanna stay up all night, and jump around until we see the sun",
    "i wanna stay up all night, and find a girl and tell her she's the one",
    "hold on to the feeling, and don't let it go",
    "'cause we got the floor now, get out of control",
    "i wanna stay up all night, and do it all with you",
    "up, up, up all night like this, all night, hey",
    "don't even care about the table breaking, we only wanna have a laugh (up, up, up all night)",
    "i'm only thinking 'bout this girl i'm seeing, i hope she'll wanna kiss me back (up, up, up all night)",
    "he takes your hand, i die a little",
    "i watch your eyes and i'm in riddles, why can't you look at me like that?",
    "when you walk by, i try to say it, but then i freeze, and never do it",
    "my tongue gets tied, the words get trapped",
    "i hear the beat of my heart getting louder, whenever i'm near you",
    "but i see you with him slow dancing",
    "tearing me apart 'cause you don't see whenever you kiss him, i'm breaking",
    "oh how i wish that was me",
    "he looks at you, the way that i would",
    "does all the things, i know that i could",
    "if only time, could just turn back",
    "'cause i got three little words that i've always been dying to tell you",
    "with my hands on your waist, while we dance in the moonlight",
    "i wish it was me, that you'll call later on 'cause you wanna say good night",
    "can't ever get it right, no matter how hard i try",
    "and i've tried, well, i put up a good fight",
    "but your words cut like knives, and i'm tired",
    "as you break my heart again this time",
    "tell me i'm a screwed up mess, that i never listen, listen",
    "tell me you don't want my kiss, that you need your distance, distance",
    "tell me anything but don't you say he's what you're missing, baby",
    "if he's the reason that you're leaving me tonight",
    "spare me what you think, and tell me a lie",
    "well, you're the charming type",
    "that little twinkle in your eye, gets me every time",
    "and well, there must've been a time, i was the reason for that smile",
    "so keep in mind, as you take what's left of you and i",
    "tell me a lie",
    "now that you can't have me, you suddenly want me",
    "now that i'm with somebody else, you tell me you love me",
    "i slept on your doorstep, begging for one chance",
    "now that i finally moved on, you say that you missed me all along",
    "who do you think you are?",
    "who do you think you are? who do you think i am?",
    "you only love to see me breaking",
    "you only want me 'cause i'm taken",
    "you don't really want my heart",
    "no, you just like to know you can, still be the one who gets it breaking",
    "you only want me when i'm taken",
    "you're messing with my head, girl that's what you do best",
    "saying there's nothing you won't do, to get me to say yes",
    "you're impossible to resist, but i wouldn't bet your heart on it",
    "it's like i'm finally awake, and you're just a beautiful mistake",
    "thank you for showing me, who you are underneath",
    "no, thank you, i don't need another heartless misery",
    "you think i'm doing this to make you jealous",
    "and i know that you hate to hear this, but this is not about you anymore",
    "give you this, give you that, blow a kiss, take it back",
    "if i looked inside your brain, i would find lots of things",
    "clothes, shoes, diamond rings, stuff that's driving me insane",
    "you could be preoccupied, different date, every night",
    "you just got to say the word, but you're not into them at all",
    "you just want materials",
    "i should know because i've heard, when girls say",
    "i want, i want, i want, but that's crazy",
    "i want, i want, i want, and that's not me",
    "i want, i want, i want, to be loved by you",
    "you've got everything you need, but you want accessories, got to hold it in your hand",
    "if i changed the world for you, i bet you wouldn't have a clue",
    "don't you know that i can't stand, when girls say",
    "i wanna, i'll stay true, i wanna, if you knew",
    "what you put me through, but you want, you want, you want me to love you too",
    "you know i've always got your back, girl",
    "so let me be the one you come running to, running to, r-r-running",
    "i see it's just a matter of fact, girl, you just call my name",
    "i'll be coming through, coming through, i'll keep coming",
    "i'll keep coming",
    "on the other side of the world, it don't matter",
    "i'll be there in two, i'll be there in two, o'll be there in two",
    "i still feel it every time, it's just something that you do",
    "now ask me why i want to",
    "it's everything about you, you, you, everything that you do, do, do",
    "from the way that we touch, baby, to the way that you kiss on me",
    "it's everything about you, you, you, the way you make it feel, new, new, new",
    "like every party is just us two, and there's nothin' i could point to",
    "it's everything about you",
    "yes, i like the way you smile with your eyes",
    "other guys see it but don't realise that it's my-my loving",
    "there's something about your laugh that it makes me want to have to",
    "there's nothing funny so we laugh at no-no-nothing",
    "every minute's like the last so let's just take it real slow",
    "forget about the clock that's tick-tick-ticking",
    "and you have always been the only one i wanted",
    "and i wanted you to know without you, i can't face it",
    "all we want to have is fun, but they say that we're too young",
    "circles, we're going in circles, dizzy's all it makes us",
    "we know where it takes us, we've been before",
    "closer, maybe looking closer, there's more to discover",
    "find out what went wrong without blaming each other",
    "think that we got more time, when we're falling behind, gotta make up our minds",
    "or else we'll play, play, play all the same old games",
    "and we wait, wait, wait for the end to change",
    "and we take, take, take it for granted that we'll be the same",
    "but we're making all the same mistakes",
    "wake up, we both need to wake up",
    "maybe if we face up to this, we can make it through this",
    "closer, maybe we'll be closer, stronger than we were before, yeah, make this something more, yeah",
    "yeah, yeah, that's what crazy is",
    "when it's broken, you say there's nothing to fix",
    "and you pray, pray, pray that everything will be okay while you're making all the same mistakes",
    "don't look back",
    "but if we don't look back, we're only learning then how to make all the same, same mistakes again",
    "i, i wanna save ya, wanna save your heart tonight",
    "he'll only break ya, leave you torn apart, oh",
    "it's a quarter to three, can't sleep at all",
    "he's so overrated",
    "if you told me to jump, i'd take the fall, and he wouldn't take it",
    "all that you want's under your nose, yeah",
    "you should open your eyes, but they stay closed, closed",
    "i can't be no superman, but for you i'll be super human",
    "oh, now you're at home, and he don't call",
    "cause he don't adore ya, to him you are just another doll",
    "and i tried to warn ya, what you want, what you need has been right here, yeah",
    "i can see that you're holding back those tears, tears",
    "up, up and away, i'll take you with me",
    "i wanna save ya, save ya, save ya tonight",
    "the light shines, it's getting hot on my shoulder",
    "i don't mind, this time it doesn't matter",
    "'cause your friends,they look good and you look better",
    "don't you know all night i've been waiting for a girl like you to come around, 'round, 'round?",
    "under the lights tonight, you turned around, and you stole my heart",
    "with just one look, when i saw your face, i fell in love",
    "it took a minute girl to steal my heart tonight",
    "with just one look, yeah, i waited for a girl like you",
    "i'm weaker, my worlds fall and they hit the ground",
    "oh life, come on head, don't you fail me now?",
    "i start to say, 'i think i love you', but I make no sound",
    "there is no other place that I would rather be, than right here with you tonight",
    "as we lay on the ground i put my arms around you, and we can stay here tonight",
    "'cause there's so much that i wanna say, i wanna say",
    "from the moment i met you, everything changed",
    "i knew i had to get you, whatever the pain",
    "i had to take you and make you mine",
    "i would walk through the desert, i would walk down the aisle",
    "i would swim all the oceans just to see you smile, whatever it takes is fine",
    "so put your hands up, cause it's a stand up",
    "and i won't be leaving 'til i  finish stealing every piece of your heart, every piece of your heart",
    "i know your hearts been broken, but don't you give up",
    "i'll be there, yeah i know it, To fix you with love",
    "it hurts me to think that you've ever cried",
    "and i will steal us a car",
    "and i will steal us a car, and we will drive to the stars",
    "i will give you the moon, it's the least i can do if you give me the chance",
    "you can call me a thief, (i'm a thief, i'm a thief)",
    "i'm only here, because you stole my heart",
    "shut the door, turn the light off",
    "if i wanna be with you, i wanna feel your love",
    "i wanna lay beside you, i cannot hide this, even though i try",
    "heartbeats harder, time escapes me",
    "trembling hands touch skin, it makes this harder",
    "and the tears stream down my face",
    "if we could only have this life for one more day",
    "if we could only turn back time",
    "you know i'll be your life, your voice, your reason to be",
    "my love, my heart is breathing for this moment, in time",
    "i'll find the words to say, before you leave me today",
    "close the door, throw the key",
    "don't wanna be reminded, don't wanna be seen, don't wanna be without you",
    "my judgement's clouded like tonight's sky",
    "hands are silent, voice's numb",
    "try to scream out, my lungs, it makes this harder",
    "flashing lights in my mind, going back to the time",
    "playing games in the street, kicking balls at my feet",
    "there's a numb in my toes, standing close to the edge",
    "there's a pile of my clothes, at the end of your bed",
    "as i feel myself fall, make a joke of it all",
    "it's not me, it's not you, there's a reason",
    "i'm just tryna read the signals i'm receiving",
    "just like a stone on fire, can you feel it?",
    "i don't know about you, girl, but i believe it",
    "words will be just words 'til you bring them to life",
    "i'll lift you up, i'll never stop",
    "you know i'll take you to another world",
    "i'll build you up, i'll never stop",
    "every day, in every way, oh-oh-oh, i'll lift you up, i'll never stop",
    "one for me, one for you, what you doing?",
    "girl, the music sounds so good when you're movin'",
    "let me take you higher, let me prove it, 'cause, hey, hey, pretty girl, I believe it",
    "baby, let me find out your secret, just let me in and let me show you that i keep it",
    "close to my heart, jump in the deep end, just let me in and let me show you what i'm meaning",
    "we've got a bit of love-hate",
    "you take me to the edge, then you hit the brakes",
    "i-i-i say, 'It's over' one day, but then i'm crawling back, begging you to stay",
    "we make up, and we break up all the time (hey-ey)",
    "i'll say that i hate a song, then you'll go request it the whole night long",
    "some people say it's so wrong, but even when we fight, girl, you turn me on",
    "we make up, and we break up all the time",
    "we're like, na, na, na (na, na, na)",
    "then we're like, yeah, yeah, yeah (yeah, yeah, yeah)",
    "always like, na, na, na (na, na, na)",
    "then we're like, yeah, yeah, yeah (yeah, yeah, yeah)",
    "no, we can't make up our minds, 'cause when we think we got it right",
    "we go, na, na, na (na, na, na), na, na, na (na, na, na)",
    "you wanna party too late, but when I do the same, all you do is complain",
    "you know that it drives me insane, but when i get with you, girl, you make it okay",
    "na, na, na (ah-ah), yeah, yeah, yeah (ah-ah)",
    "Na, na, na, na, na, na, na, na, na, na, na, na",
    "we go, na, na, na",
    "i keep playing it inside my head, all that you said to me",
    "i lie awake just to convince myself, this wasn't just a dream",
    "'cause you were right here, and i should've taken the chance",
    "but i got so scared, and i lost the moment again",
    "it's all that i can think about, oh, you're all that i can think about",
    "is your heart taken? is there somebody else on your mind?",
    "i'm so sorry, i'm so confused",
    "just tell me, am i out of time?",
    "is your heart breaking? how do you feel about me now?",
    "i can't believe i let you walk away when, when i should have kissed you",
    "i should've, i should've, oh, i should have kissed you",
    "every morning when i leave my house, i always look for you, yeah",
    "i see you every time i close my eyes, what am i gonna go?",
    "and all my friends say that i'm punching over my weight",
    "but in my eyes i saw how you're looking at me",
    "hey, girl, i'm waiting on you, i'm waiting on you",
    "come on, and let me sneak you out, and have a celebration, a celebration",
    "the music up, the window's down",
    "yeah, we'll be doing what we do, just pretending that we're cool and we know it too",
    "yeah, we'll keep doing what we do, just pretending that we're cool, so tonight",
    "let's go crazy, crazy, crazy 'til we see the sun",
    "i know we only met, but let's pretend it's love",
    "and never, never, never stop for anyone",
    "tonight, let's get some, and live while we're young",
    "hey, girl, it's now or never, it's now or never, don't overthink, just let it go",
    "and if we get together, yeah, get together, don't let the pictures leave your phone, ooh",
    "oh, i just wanna take you anywhere that you'd like",
    "we could go out any day, any night",
    "baby, i'll take you there, take you there, baby, i'll take you there, yeah",
    "oh, tell me, tell me, tell me how to turn your love on",
    "you can get, get anything that you want",
    "baby, just shout it out, shout it out, baby, just shout it out, yeah",
    "and if you, you want me too, let's make a move",
    "yeah, so tell me, girl, if every time we touch, you get this kinda rush",
    "baby, say, yeah, yeah, yeah, yeah, yeah, yeah",
    "if you don't wanna take it slow, and you just wanna take me home",
    "and let me kiss you",
    "oh, baby, baby, don't you know you got what i need?",
    "looking so good from your head to your feet",
    "come on, come over here, over here, come on, come over here, yeah",
    "oh, i just wanna show you off to all of my friends",
    "making them drool down their chinny-chin-chins",
    "baby, be mine tonight, mine tonight, baby, be mine tonight, yeah",
    "c'mon, na-na-na-na-na-na-na-na",
    "na-na-na-na-na-na-na-na",
    "your hand fits in mine like it's made just for me",
    "your hand fits in mine like it's made just for me, but bear this mind, it was meant to be",
    "and i'm joining up the dots, with the freckles on your cheeks, and it all makes sense to me",
    "i know you've never loved the crinkles by your eyes when you smile",
    "you've never loved your stomach or your thighs",
    "the dimples in your back at the bottom of your spine, but i'll love them endlessly",
    "i won't let these little things slip out of my mouth",
    "but if i do, it's you, oh, it's you, they add up to",
    "i'm in love with you and all these little things",
    "you can't go to bed without a cup of tea and maybe that's the reason that you talk in your sleep",
    "and all those conversations are the secrets that i keep, though it makes no sense to me",
    "i know you never loved the sound of your voice on tape",
    "you never want to know how much you weight",
    "you still have to squeeze into your jeans, but you're perfect to me",
    "you'll never love yourself half as much as I love you",
    "and you'll never treat yourself right darling, but i want you to",
    "if i let you know, i'm here for you, maybe you'll love yourself like i love you, oh",
    "the one that i came with, she had to go",
    "but you look amazing, standing alone",
    "so c'mon, c'mon, move a little closer now",
    "c'mon, c'mon, ain't way you're walkin' out",
    "c'mon, c'mon, show me what you're all about",
    "yeah, i've been watchin' you all night",
    "there's somethin' in your eyes",
    "say c'mon, c'mon and dance with me baby",
    "yeah, the music is so loud",
    "i wanna be yours now",
    "the one that i came with didn't know how to move",
    "the way that you let your hair down, i can tell that you do",
    "every step i take, i'm feelin' more and more",
    "she's callin' out, she's a lucky girl",
    "my heart is racin', she's turnin' around",
    "i reach for her hand and i say",
    "baby, i, i wanna know what you think when you're alone",
    "is it me, yeah? are you thinking of me, yeah, oh?",
    "we've been friends now for a while, wanna know that when you smile",
    "girl, what would you do? would you wanna stay, if i were to say?",
    "i wanna be last, yeah, baby, let me be your, let me be your last first kiss",
    "baby, let me be your, let me be your last first kiss",
    "wanna be the first to take it all the way like this",
    "and if you-ou-ou only knew-ew-ew",
    "baby, tell me what to change",
    "i'm afraid you'll run away if i tell you, what i wanted to tell you, yeah",
    "maybe i just gotta wait, maybe this is a mistake",
    "i'm a fool, yeah, baby, i'm just a fool, yeah; oh, oh",
    "baby, you've got me sick, i don't know what i did",
    "need to take a break and figure it out, yeah",
    "got your voice in my head sayin', 'Let's just be friends'",
    "can't believe the words came out of your mouth, yeah",
    "i'm tryna be okay, i'm tryna be alright",
    "but seeing you with him, just don't feel right",
    "and i'm like (oww!), never thought it'd hurt so bad",
    "getting over you-ohh and (oww!)",
    "you're giving me a heart attack, looking like you do-oh",
    "'cause you're all i ever wanted, thought you would be the one",
    "thought you would be the one, it's (oww!)",
    "giving me a heart attack getting over you-oh-oh-oh",
    "yeah! baby, now that you're gone, i can't stand dumb love songs",
    "missing you is all i'm thinking about, yeah",
    "everyone's telling me, i'm just too blind to see, how you messed me up, i'm better off now, yeah",
    "oh, oh, oh, oh, oh, oh, oh-oh, oh... (oww!)",
    "you're giving me a heart attack",
    "oww!",
    "do you remember summer '09, wanna go back there every night",
    "just can't lie it was the best time of my life, lying on the beach as the sun blew out",
    "playing this guitar by the fire too loud, oh my my they could never shut us down",
    "i used to think that i was better alone, why did i ever want to let you go",
    "under the moonlight as we stared at the sea, the words you whispered i will always believe",
    "i want you to rock me, mmm, rock me, mmm, rock me, yeah",
    "i want you to hit the pedal heavy metal show me you care",
    "yeah we were together summer '09, wanna roll back like press and rewind",
    "you were mine and we never said goodbye",
    "R-O-C-K me again",
    "the end of the night, we should say goodbye",
    "but we carry on, while everyone's gone",
    "never felt like this before, are we friends or are we more",
    "as i'm walking towards the door, i'm not sure",
    "but baby if you say you want me to stay, i'll change my mind",
    "'cause i don't wanna know i'm walking away, if you'll be mine",
    "won't go, won't go, so baby if you say you want me to stay",
    "stay for the night, i'll change my mind",
    "lean in when you laugh, we take photographs",
    "there's no music on, but we dance along",
    "lately i found myself thinking (thinking), been dreaming about you a lot (a lot)",
    "and up in my head i'm your boyfriend (boyfriend), but that's one thing you've already got",
    "he drives to school every morning (morning), while i walk alone in the rain (in the rain)",
    "he'd kill me without any warning (warning), if he took a look in my brain",
    "would he say he's in L-O-V-E?",
    "well, if it was me, then i would, i would",
    "would he hold you when you're feeling low? baby, you should know that i would, i would",
    "back in my head, we were kissing, i thought things were going alright (alright, alright, alright)",
    "with a sign on my back saying, 'kick me', reality ruined my life (go, Tommo, go)",
    "reality ruined my life",
    "feels like i'm constantly playing, a game that i'm destined to lose",
    "'cause i can't compete with your boyfriend, he's got 27 tattoos",
    "said i'd never leave her, 'cause her hands fit like my t-shirt",
    "tongue-tied over three words, cursed, running over thoughts that make my feet hurt",
    "bodies intertwined with her lips",
    "now she's feeling so low since she went solo, hole in the middle of my heart like a polo",
    "and it's no joke to me, so can we do it all over again?",
    "if you're pretending from the start, like this with a tight grip",
    "then my kiss can mend your broken heart, i might miss everything you said to me",
    "and i can lend you broken parts, that might fit like this",
    "and i will give you all my heart, so we can start it all over again",
    "again, we take the same road, two days in the same clothes",
    "and i know just what she'll say if i make all this pain go",
    "can we stop this for a minute?",
    "you know, i can tell that your heart isn't in it or with it",
    "and tell me with your mind, body and spirit, i can make your tears fall down",
    "like the showers that are british, whether we're together or apart",
    "we can both remove the masks, and admit we regret it from the start",
    "you'll never know how to make it on your own, and you'll never show weakness for letting go",
    "i guess it's still hard if the seed's sown, but, do you really want to be alone?",
    "whenever i close my eyes, i picture you there",
    "i'm looking out at the crowd, you're everywhere",
    "i'm watching you from the stage, yeah, your smile is on every face now",
    "but every time you wake up, you're hearing me say goodbye",
    "baby, you don't have to worry",
    "i'll be coming back for you, back for you, back for you, you",
    "lately, i've been going crazy",
    "i've never been so into somebody before, and every time we both touch, i only want more",
    "so tell me nothing's gonna change, yeah, and you won't ever walk away, yeah",
    "'cause even though every night, you'll know what i'll say goodbye",
    "right back for you, ooh-oh",
    "people say we shouldn't be together, we're too young to know about forever",
    "but i say, 'they don't know what they're talk-, talk-, talking about (talk-, talk-, talking about)",
    "'cause this love is only gettin' stronger, so, i don't wanna wait any longer",
    "i just wanna tell the world that you're mine, girl, oh",
    "they don't know about the things we do, they don't know about the i-love-yous",
    "but i bet you if they only knew (they don't know), they would just be jealous of us",
    "they don't know about the up-all-nights, they don't know i've waited all my life",
    "just to find a love that feels this right (they don't know)",
    "baby, they don't know about, they don't know about us",
    "one touch, and i was a believer, every kiss, it gets a little sweeter",
    "it's getting better, keeps getting better all the time, girl",
    "they don't know how special you are, they don't know what you've done to my heart",
    "they can say anything they want, 'cause they don't know about us",
    "they don't know what we do best, that's between me and you, our little secret",
    "yeah, oh ooh ooh, ooh ooh, ooh",
    "can't believe you're packing your bags, trying so hard not to cry",
    "had the best time and now it's the worst time, but we have to say goodbye",
    "don't promise that you're gonna write, don't promise that you'll call",
    "just promise that you won't forget we had it all",
    "'cause you were mine for the summer, now we know it's nearly over",
    "feels like snow in September, but i always will remember",
    "you were my summer love, you always will be my summer love",
    "wish that we could be alone now, if we could find some place to hide",
    "make the last time just like the first time, push a button and rewind",
    "don't say the word that's on your lips, don't look at me that way",
    "just promise you'll remember, when the sky is grey",
    "so please don't make this any harder, we can't take this any farther",
    "and i know there's nothing that i wanna change, change",
    "she sneaks out in the middle of the night, yeah, tight dress with the top cut low",
    "she's addicted to feeling of letting go, oh, ohoo, let it go",
    "she walks in and the room just lights up",
    "but she don't want anyone to know, that i'm the only one who gets to take her home, oh, ohoo",
    "but everytime i tell her that i want more, she closes the door",
    "she's not afraid of all the attention, she's not afraid of running wild",
    "how come she's so afraid of falling in love, she's not afraid of scary movies",
    "she likes the way we kiss in the dark, but she's so afraid of f-f-falling in love",
    "maybe she's just trying to test me, wanna see how hard i'm gonna work",
    "wanna see if i can really tell how much she's worth, what your worth",
    "or maybe all her friends have told her, 'don't' get closer he'll just break your heart'",
    "but either way she sees in me and it's just so hard (so hard)",
    "'cause every time i tell her how i feel, she says it's not real",
    "what about all the things we said, talking on the phone so late",
    "i can't let her get away from me",
    "when i say that i can't do it no more, she's back in my door",
    "girl, it should be me, driving to your house",
    "knocking on your door, kissing you on the mouth, holding on your hand",
    "dancing in the dark, 'cause i was the only one who loved you from the start",
    "but now when i see you with him it tears my world apart",
    "because, i've been waiting all this time to finally say it",
    "but now i see your heart's been taken and nothing could be worse",
    "baby, i loved you first",
    "had my chances, could've been where he is standing",
    "that's what hurts the most, girl, i came so close",
    "but now you'll never know, baby, i loved you first",
    "girl, it should be me, calling on your phone, saying you're the one, and that i'll never let you go",
    "i never understood, what love was really like, but i felt it for the first time looking in your eyes",
    "but now when i see you with him, my whole world falls apart",
    "the first touch, the first kiss, first girl to make me feel like this",
    "heartbreak, it's killing me, i loved you first, why can't you see?",
    "you're so pretty when you cry, when you cry",
    "wasn't ready to hear you say, 'goodbye', now you're tearing me apart, tearing me apart",
    "you're so london, your own style, your own style, and together we're so good",
    "so girl, why are you tearing me apart, tearing me apart? you're tearing me apart",
    "did i do something stupid?",
    "yeah, girl, if i blew it, just tell me what i did, let's work through it",
    "there's gotta be some way, to get you to want me, like before",
    "'cause no one ever looks so good in a dress",
    "and it hurts, 'cause i know you won't be mine tonight",
    "no one ever makes me feel like you do when you smile",
    "baby, tell me how to make it right",
    "now all of my friends say, it's not really worth it, but even if that's true",
    "no one in the world could stop me from not movin' on, baby, even if i wanted to",
    "nobody compares to you",
    "we're so Paris, when we kissed, when we kissed, i remember the taste of your lipstick",
    "now you're tearing up my heart, tearing up my heart, you're tearing up my heart",
    "hello, hello, i know it's been a while",
    "but baby, i got something that i really wanna let you know, yeah, something that i wanna let you know",
    "you say, you say to everybody that you hate me, couldn't blame you 'cause i know i left you all alone, yeah",
    "i know that i left you all alone, and yeah, now i'm back at your door",
    "you're lookin' at me unsure, i should've seen it before",
    "you're all i think about, baby",
    "i was so stupid for letting you go, but i, i, i know you're still the one",
    "you might have moved on, but girl you should know",
    "that i, i, i know you're still the one",
    "i know i say it too much, but i will never give up",
    "i was so stupid for letting you go, but i, i, i know you're still the one",
    "hello, hello, i'm really hoping you'll forgive me",
    "i keep talking, begging, tell me what i wanna hear, yeah, girl just tell me what I wanna hear",
    "i tried, i tried to start again and find somebody",
    "but i remember all the times and all the words we said, yeah, i can't get it out of my head",
    "hey you, you're still the one",
    "am i asleep, am i awake, or somewhere in between?",
    "i can't believe that you are here and lying next to me",
    "or did i dream that we were perfectly entwined? like branches on a tree, or twigs caught on a vine?",
    "like all those days and weeks and months i tried to steal a kiss",
    "and all those sleepless nights and daydreams where i pictured this",
    "i'm just the underdog who finally got the girl and i am not ashamed to tell it to the world",
    "truly, madly, deeply, i am foolishly, completely falling",
    "and somehow you kicked all my walls in, so baby, say you'll always keep me",
    "truly, madly, crazy, deeply in love with you, in love with you",
    "should i put coffee and granola on a tray in bed, and wake you up with all the words that i still haven't said?",
    "and tender touches, just to show you how i feel, or should i act so cool like it was no big deal?",
    "wish i could freeze this moment in a frame and stay like this",
    "i'll put this day back on replay and keep reliving it",
    "'cause here's the tragic truth if you don't feel the same",
    "my heart would fall apart if someone said your name",
    "i hope i'm not a casualty, i hope you won't get up and leave",
    "may not mean that much to you, but to me it's everything, everything",
    "b-b-b-baby c'mon over, i don't care if people find out (da-da, da-da-da, da, da, da, da)",
    "they say that we're no good together, and it's never gonna work out (da-da, da-da-da, da, da, da, da)",
    "but baby you got me moving too fast, 'cause i know you wanna be bad",
    "and girl when you're lookin' like that (da-da, da-da-da), i can't hold back",
    "'cause you, you've got this spell on me, i don't know what to believe",
    "kiss you once now i can't leave, 'cause everything you do is magic",
    "but everything you do is magic",
    "so l-l-let them take the pictures, spread it all around the world now (da-da, da-da-da, da, da, da, da)",
    "i wanna put it on my record, i want everyone to know now (da-da, da-da-da, da, da, da, da)",
    "don't try to make me stay, or ask if i'm okay, i don't have the answer",
    "don't make me stay the night, or ask if i'm alright, i don't have the answer",
    "heartache doesn't last forever, i'll say i'm fine",
    "midnight ain't no time for laughing, when you say goodbye",
    "it makes your lips so kissable, and your kiss unmissable",
    "your fingertips so touchable, and your eyes irresistible",
    "i've tried to ask myself, should i see someone else? i wish i knew the answer",
    "but i know, if i go now, if i leave, then i'm on my own tonight, i'll never know the answer",
    "midnight doesn't last forever, dark turns to light",
    "heartache flips my world around, i'm falling down, down, down, that's why",
    "maybe it's the way she walked (wow), straight into my heart and stole it",
    "through the doors and past the guards (wow), just like she already owned it",
    "i said, 'can you give it back to me?' she said, 'never in your wildest dreams'",
    "and we danced all night to the best song ever",
    "we knew every line, now i can't remember how it goes but i know that i won't forget her",
    "'cause we danced all night to the best song ever",
    "i think it went oh, oh, oh, i think it went yeah, yeah, yeah, i think it goes (ooh)",
    "said her name was Georgia Rose (wow) and her daddy was a dentist",
    "said i had a dirty mouth (i got a dirty mouth), but she kissed me like she meant it",
    "i said, 'can i take you home with me?' she said, 'never in your wildest dreams'",
    "you know, i know, you know i'll remember you and i know, you know, i know you'll remember me",
    "and you know, i know, you know i'll remember you",
    "and i know, you know, i hope you'll remember how we danced, how we danced (one, two, one, two, three)",
    "it was the best song ever",
    "written in these walls are the stories that i can't explain",
    "i leave my heart open but it stays right here empty for days",
    "she told me in the morning she don't feel the same about us in her bones",
    "it seems to me that when i die, these words will be written on my stone",
    "and i'll be gone, gone tonight, the ground beneath my feet is open wide",
    "the way that i been holdin' on too tight, with nothin' in between",
    "the story of my life, i take her home",
    "i drive all night to keep her warm and time is frozen (the story of, the story of)",
    "the story of my life, i give her hope, i spend her love until she's broke inside",
    "written on these walls are the colors that i can't change",
    "leave my heart open, but it stays right here in its cage",
    "i know that in the morning, i'll see us in the light up on the hill",
    "although i am broken, my heart is untamed still",
    "and i'll be gone, gone tonight, the fire beneath my feet is burnin' bright",
    "and i've been waiting for this time to come around, but, baby, runnin' after you is like chasin' the clouds",
    "the front pages are your pictures, they make you look so small",
    "how could someone not miss you at all? (oh-ah-oh)",
    "i never would mistreat ya, oh, i'm not a criminal",
    "i speak a different language, but i still hear your call",
    "diana, let me be the one to light a fire inside those eyes",
    "you've been lonely, you don't even know me, but i can feel you crying",
    "diana, let me be the one to lift your heart up, and save your life",
    "i don't think you even realize, baby, you'd be saving mine (oh, oh-oh)",
    "it's only been four months but you've fallen down so far, how could someone mislead you at all? (oh-ah-oh)",
    "i wanna reach out for ya, i wanna break these walls",
    "we all need something, this can't be over now",
    "if i could hold ya, swear i'd never put you down",
    "one, two, three!",
    "straight off the plane to a new hotel, just touched down, you could never tell",
    "ah, a big house party with a crowded kitchen, people talk (shh) but we don't listen",
    "tell me that i'm wrong but i do what i please, way too many people in the addison lee",
    "now i'm at the age when i know what i need, oh, whoa",
    "midnight memories, oh-oh-oh-oh-oh",
    "baby, you and me, stumblin' in the street, singin', singin', singin', singin'",
    "anywhere we go,never say no, just do it, do it, do it, do it",
    "five foot something with the skinny jeans, don't look back, baby, follow me",
    "i don't know where i'm going but i'm finding my way",
    "same old sh- but a different day",
    "you and me and all our friends, i don't care how much we spend, baby, this is what the night is for",
    "i know nothing's making sense, for tonight let's just pretend, i don't wanna stop so give me more",
    "i figured it out, i figured it out from black and white",
    "seconds and hours, maybe they had to take some time",
    "i know how it goes, i know how it goes from wrong and right",
    "silence and sound, did they ever hold each other tight like us? did they ever fight like us?",
    "you and i, we don't wanna be like them",
    "we can make it 'til the end, nothing can come between you and i",
    "not even the Gods above, can separate the two of us",
    "i figured it out, saw the mistakes of up and down",
    "meet in the middle, there's always room for common ground",
    "i see what it's like, i see what it's like for day and night",
    "never together, 'cause they see things in a different light like us, they never tried like us",
    "been a lot of places, i've been all around the world",
    "seen a lot of faces, never knowing where i was",
    "on the horizon hmm, well i know, i know, i know, i know, the sun will be rising back home",
    "living out of cases, and packing up and taking off",
    "made a lot of changes, but not forgetting who i was",
    "on the horizon, ooh, well i know, i know, i know, i know, the moon will be rising back home",
    "don't forget where you belong, home",
    "if you ever feel alone, don't",
    "you were never on your own and the proof is in this song",
    "i've been away for ages, but i got everything i need",
    "i'm flicking through the pages, i've written in my memory",
    "i feel like i'm dreaming, oh, so i know, i know, i know, i know, that i'm never leaving",
    "lights off when they should be on, even stars in the skies, they're wrong",
    "short days when the nights are long, when i think of the things i've done",
    "don't matter how far i've gone, i'm always free to run home",
    "my hands, your hands, tied up like two ships",
    "drifting, weightless, waves try to break it",
    "i'd do anything to save it, why is it so hard to save it?",
    "my heart, your heart, sit tight like bookends",
    "pages between us, written with no end",
    "so many words we're not saying, don't wanna wait 'til it's gone",
    "you make me strong",
    "i'm sorry if i say, 'i need you', but i don't care, i'm not scared of love",
    "'cause when i'm not with you, i'm weaker",
    "is that so wrong? is it so wrong, that you make me strong?",
    "think of how much love that's been wasted",
    "people always trying to escape it, move on to stop their heart breaking",
    "but there's nothing i'm running from, you make me strong",
    "so, baby, hold on to my heart, oh, need you to keep me from falling apart",
    "i'll always hold on,'cause you make me strong",
    "you don't understand, you don't understand, what you do to me when you hold his hand",
    "we were meant to be but a twist of fate, made it so you had to walk away",
    "'cause we're on fire, we are on fire, we're on fire now",
    "i don't care what people say when we're together, you know i wanna be the one to hold you when you sleep",
    "i just want it to be you and i forever, i know you wanna leave",
    "so c'mon baby be with me, so happily",
    "it's four a.m. and i know that you're with him, i wonder if he knows that i touched your skin",
    "and if he feels my traces in your hair, sorry, love, but i don't really care",
    "sorry, love, but i don't really care",
    "oh, oh, oh, oh, oh, oh, oh, oh, we're on fire now",
    "lights go down, and the night is calling to me, yeah",
    "i hear voices singing songs in the street, and i know that we won't be going home for so long, for so long",
    "but i know that i won't be on my own, yeah, i love this feeling and",
    "right now, i wish you were here with me (Oh-ooh)",
    "'cause right now, everything is new to me (oh-ooh)",
    "you know i can't fight the feeling and every night i feel it",
    "right now, i wish you were here with me (oh-ooh)",
    "late night spaces with all our friends, you and me, yeah",
    "love these faces, just like how it used to be",
    "and we won't be going home, for so long, for so long",
    "but i know, i won't be on my own, on my own, i'm feeling like",
    "and i could do this forever (woah-oh-oh, woah-oh-oh), and let's go crazy together (woah-oh-oh, woah-oh-oh)",
    "lights go down, and i hear you calling to me, yeah",
    "little black dress, just walked into the room",
    "makin' heads turn, can't stop looking at you",
    "it's so right, it's so right, it's so right you know",
    "little black dress, did you come here alone?",
    "it's too late, it's too late, it's too late to go home",
    "it's so right, it's so right, oit's so right you know",
    "i wanna see the way you move for me baby",
    "little black dress, who you doin' it for?",
    "little black dress, i can't take anymore",
    "little black dress, what's your favorite song?",
    "little black dress, i won't do you no harm",
    "you tell me that you're sad and lost your way",
    "you tell me that your tears are here to stay, but i know you're only hiding and i just wanna see you",
    "you tell me that you're hurt and you're in pain and i can see your head is held in shame",
    "but i just wanna see you smile again, see you smile again",
    "but don't burn out, even if you scream and shout",
    "it'll come back to you and i'll be here for you",
    "it'll come back to you and i'll be here for you",
    "oh i will carry you over, fire and water for your love",
    "and i will hold you closer, hope your heart is strong enough",
    "when the night is coming down on you, we will find a way through the dark",
    "i wish that i could take you to the stars, i'd never let you fall and break your heart",
    "and if you wanna cry or fall apart, i'll be there to hold you",
    "you tell me that you hurt, it's all in vain, but i can see your heart can love again",
    "and i remember you laughing, so let's just laugh again",
    "and you don't need, you don't need to worry",
    "and you will see it's easy to be loved, i know you wanna be loved",
    "one day you'll come into my world and say it all, you say we'll be together even when you're lost",
    "one day you'll say these words, i thought you'll never say, you say we're better off together in our bed",
    "i want you here with me like how i pictured it, so i don't have to keep imagining",
    "come on, jump out at me, come on, bring everything",
    "is it too much to ask for something great?",
    "the script was written and i could not change a thing",
    "i want to rip it all to shreds and start again",
    "one day i'll come into your world and get it right, i'll say we're better off together here tonight",
    "you're all i want, so much it's hurting",
    "if this room was burning, i wouldn't even notice",
    "'cause you've been taking up my mind, with your little white lies, little white lies",
    "you say, it's getting late, it's getting late",
    "and you don't know if you can stay, if you can stay",
    "but you, you don't tell the truth, no you, you like playing games",
    "your hands touching me, they're touching me, and your eyes keep saying things",
    "they say what we do, when it's only me and you, i can't concentrate",
    "that's all i'm thinking about, all i keep thinking about, everything else just fades away",
    "you say you're a good girl, but i know you would girl",
    "'cause you've been telling me all night, with your little white lies, little white lies",
    "back seat of the cab, we're in the cab",
    "my lips getting so attached, they're so attached",
    "now you wanna make some rules, now cool then we'll watch them break tonight",
    "better than words, more than a feeling (ah, ooh), crazy in love, dancing on the ceiling (ha!)",
    "every time we touch, I'm all shook up",
    "You make me wanna-, how deep is your love? god only knows, baby",
    "ooh, i don't know how else to sum it up,'cause words ain't good enough",
    "ooh, there's no way i can explain your love, no, ah-ooh, i don't know how else to sum it up",
    "'cause words ain't good enough, ooh, i can't explain your love, no",
    "it's better than words",
    "better than words, you drive me crazy, someone like you, always be my baby",
    "best i ever had, hips don't lie, you make me wanna-, one more night",
    "irreplaceable (yeah), crazy, we're crazy",
    "everyone tries (they try), to see what it feels like (feels like)",
    "but they'll never be right 'cause it's better, it's better, it's better",
    "i know you want, know you wanna take it slow, think about all the places we could go",
    "if you give in tonight, just let me set you free",
    "we'll touch the other side, just give me the key",
    "'cause we got all night and we're going nowhere",
    "why don't you stay, why don't we go there?",
    "let's take a ride out in the cold air",
    "i know the way, why don't you go there with me?",
    "say the word, say the word but don't say no",
    "skydive, you and i, with just these clothes",
    "the secret's safe with me, there's no right time or place",
    "hey, i don't want you to be the one that got away, i wanna get addicted to you, yeah",
    "you're rushing through my mind, i wanna feel the high, i wanna be addicted, don't say no",
    "he knows about you in every way, he's memorized every part of your face",
    "inside and out, baby, head to toe, yeah, he knows everything there is to know",
    "your secret tattoo, the way you change moods, the songs that you sing when you're all alone",
    "your favorite band, and the way that you dance, but baby, baby",
    "does he know you can move it like that? whoa-oh-oh-oh",
    "does he know you're out and i want you so bad, oh-oh-oh-oh",
    "tonight you're mine, baby, does he know that you'll never go back?",
    "catch your eye then you turn away, but there's no hiding the smile on your face",
    "inside and out, baby, head to toe, he's not around, girl, you let me know",
    "he knows how you dance in front of your friends, but baby, baby",
    "he'll never know the way you lie when you look at me",
    "so keep trying but you know i see, all the little things who make you who you are",
    "my mother told me i should go and get some therapy",
    "i asked the doctor, 'can you find out what is wrong with me?'",
    "i don't know why i wanna be with every girl i meet i can't control it",
    "yeah, i know it's taking over me, i'm going crazy",
    "can't contain it, so tell me just what i should do?",
    "she said, 'hey, it's alright, does it make you feel alive?'",
    "'don't look back, live your life, even if it's only for tonight'",
    "she said, 'hey, it's alright, if it makes you feel alive",
    "went to a party just after the doctor talked to me, i met a girl, i took her in up to the balcony",
    "i whispered something in her ear that i just can't repeat, she said, 'okay' but she was worried what her friends will think",
    "she's going crazy, can't contain it, she asked me, 'what should i do, oh?'",
    "we got to live before we get older, do what we like",
    "we got nothing to lose, shake off the weight of the world from your shoulders",
    "so your friend's been telling me, you've been sleeping with my sweater",
    "and that you can't stop missing me, bet my friend's been telling you",
    "i'm not doing much better, 'cause i'm missing half of me",
    "and being here without you is like i'm waking up to",
    "only half a blue sky, kinda there, but not quite, i'm walking around with just one shoe",
    "i'm half a heart without you, i'm half a man, at best, with half an arrow in my chest",
    "i miss everything we do, i'm half a heart without you",
    "forget all we said that night, no, it doesn't even matter",
    "'cause we both got split in two, if you could spare an hour or so",
    "we'll go for lunch down by the river, we can really talk it through",
    "i'm half a heart without you",
    "though i try to get you out of my head, the truth is i got lost without you",
    "she's been my queen, since we were sixteen",
    "we want the same things, we dream the same dreams, alright, alright",
    "i got it all 'cause she is the one",
    "her mum calls me love, her dad calls me son, alright, alright",
    "everybody wanna steal my girl, everybody wanna take her heart away",
    "couple billion in the whole wide world, find another one 'cause she belongs to me",
    "na na na na na na (oh, yeah), na na na na na na (alright)",
    "kisses like cream, her walk is so mean",
    "and every jaw drop, when she's in those jeans",
    "i don't exist if i don't have her, the sun doesn't shine, the world doesn't turn",
    "she knows, she knows, that i never let her down before",
    "she knows, she knows, that i'm never gonna let another take her love from me now",
    "there's a lightning in your eyes i can't deny, then there's me inside a sinking boat, running out of time",
    "without you i'll never make it out alive, but i know, yes i know we'll be alright",
    "there's a devil in your smile, it's chasing me and every time i turn around it's only gaining speed",
    "there's a moment when you finally realize, there's no way you can change the rolling tide",
    "but i know, yes i know that i'll be fine",
    "this time i'm ready to run (oh-oh), escape from the city and follow the sun",
    "'cause i wanna be yours, don't you wanna be mine?",
    "i don't wanna get lost in the dark of the night, this time i'm ready to run (oh-oh)",
    "wherever you are is the place i belong, 'cause i wanna be free",
    "and i wanna be young, i will never look back, now i'm ready to run",
    "there's a future in my life i can't foresee, unless of course i stay on course",
    "and keep you next to me, there will always be the kind that criticize",
    "i'd give everything that i got for your love",
    "i know it's been some time, but there's something on my mind",
    "you see, i haven't been the same, since that cold november day",
    "we said we needed space, but all we found was an empty place",
    "and the only things i learned, is that i need you desperately",
    "so here i am, and can you please tell me, oh",
    "where do broken hearts go?",
    "can they find their way home, back to the open arms of a love that's waiting there?",
    "and if somebody loves you, won't they always love you?",
    "i look in your eyes and i know that you still care, for me (ooh, baby)",
    "i've been around enough to know, that dreams don't turn to gold and there is no easy way",
    "no, you just can't run away and what we had was so much more than we ever had before",
    "and no matter how i try, you're always on my mind",
    "and now that i am here with you, i'll never let you go",
    "i look into your eyes and now i know, now i know",
    "i got a heart and i got a soul, believe me i will use them both",
    "we made a start, be it a false one, i know",
    "baby, i don't want to feel alone",
    "so kiss me where i lay down, my hands pressed to your cheeks, a long way from the playground",
    "i have loved you since we were 18",
    "long before we both thought the same thing, to be loved and to be in love",
    "all i can do is say that these arm are made for holding you, oh-oh",
    "i wanna love like you made me feel, when we were 18",
    "we took a chonce",
    "we took a chance, god knows we tried",
    "yet all along, i knew we'd be fine, so pour me a drink, oh love",
    "and let's split the night wide open and we'll see everything we can",
    "living love in slow motion, motion, motion",
    "hey, hey, oh, no, no, no",
    "her light is as loud as- as many ambulances as it takes to save a savior oh (woah, woah, woah)",
    "now, she floats through the room on a big balloon",
    "some say, 'she's such a fake', that her love is made up, no, no, no, no",
    "let's have another toast to the girl almighty",
    "let's pray we stay young, stay made of lightning",
    "am i the only, only believer? there's something happening here",
    "there's something happening here, i hope you feel what i'm feeling too",
    "i'd get down, i'd get down, i'd get down on my knees for you",
    "i'm like a crow on a wire, you're the shining distraction that makes me fly",
    "oh home, i'm like a boat on the water, you're the rays on the waves that calm my mind",
    "but i know in my heart, you're not a constant star, and yeah, i let you use me from the day that we first met",
    "but i'm not done yet falling for you, fool's gold",
    "and i knew that you turned it on for everyone you've met, but i don't regret",
    "falling for you, fool's gold",
    "i'm the first to admit that i'm reckless, i get lost in your beauty",
    "and i can't see, two feet in front of me",
    "and i know in my heart, you're just a moving part",
    "yeah, i know your love's not real, that's not the way it feels, that's not the way you feel",
    "goin' out tonight, changes into something red, her mother doesn't like that kind of dress",
    "everything she never had she's showin' off, drivin' too fast, moon is breakin' through her hair",
    "she's headin' for somethin' that she won't forget, havin' no regrets is all that she really wants",
    "we're only gettin' older, baby, and i've been thinkin' about it lately",
    "does it ever drive you crazy, just how fast the night changes?",
    "everything that you've ever dreamed of, disappearing when you wake up, but there's nothing to be afraid of",
    "even when the night changes, it will never change me and you",
    "chasing it tonight, doubts are runnin' 'round her head, he's waitin', hides behind a cigarette",
    "heart is beatin' loud and she doesn't want it to stop, movin' too fast, moon is lightin' up her skin",
    "she's fallin', doesn't even know it yet",
    "reminds her of the missin' piece of innocence she lost",
    "stained coffee cup, just a fingerprint of lipstick's not enough",
    "sweet (ooh), where you lay (ooh), still a trace of innocence on the pillow case",
    "waking up, beside you, i'm my loaded gun",
    "i can't contain this anymore, i'm all yours, i've got no control",
    "powerless and i don't care, it's obvious, i just can't get enough of you",
    "the pedal's down, my eyes are closed, no control",
    "the taste on my tongue, i don't want to wash away the night before",
    "in the heat (ooh), where you laid (ooh), i could stay right here and burn in it all day",
    "lost my senses, i'm defenseless, her perfume's holding me ransom",
    "sweet and sour, heart devoured, lying here, i count the hours",
    "i think i'm gonna lose my mind, somethin' deep inside me, i can't give up",
    "i think i'm gonna lose my mind, i roll and i roll 'til i'm out of luck",
    "i'm feelin' somethin' deep inside, hotter than a jet stream burnin' up",
    "i got a feelin' deep inside, it's takin', it's takin' all i've got",
    "'cause nobody knows you, baby, the way i do and nobody loves you, baby, the way i do",
    "it's been so long, it's been so long, maybe you are fireproof",
    "'cause nobody saves me, baby, the way you do",
    "i think i'm gonna win this time, ridin' on the wind and i won't give up",
    "i think i'm gonna win this time, i roll and i roll 'til i change my luck",
    "who's gonna be the first one to start the fight? who's gonna be the first one to fall asleep at night?",
    "who's gonna be the last one to drive away? who's gonna be the last one to forget this place?",
    "we keep taking turns, will we ever learn?",
    "oh spaces between us, keep getting deeper",
    "it's harder to reach you, even though i try",
    "spaces between us, hold all our secrets",
    "leaving us speechless and i don't know why",
    "who's gonna be the first to say goodbye?",
    "we keep taking turns, will we ever learn? when will we learn?",
    "who's that shadow holding me hostage? i've been here for days",
    "who's this whisper telling me that i'm never gonna get away?",
    "i know they'll be coming to find me soon, but i fear i'm getting used to being held by you",
    "oh, baby, look what you've done to me, oh, baby, look what you've done now",
    "oh, baby, i'll never leave you if you keep holding me this way (oh-oh-oh-oh)",
    "who's this man that's holding your hand and talking about your eyes? (oh-oh-oh-oh)",
    "used to sing about being free, but now he's changed his mind (oh-oh-oh-oh)",
    "i know they'll be coming to find me soon, but my stockholm syndrome is in your room, yeah, i fell for you",
    "i know you say that you don't like it complicated",
    "that we should try to keep it simple, but love is never ever simple",
    "someday, you're gonna see the things that i see, you're gonna want air that i breathe",
    "you're gonna wish you never left me",
    "here we go again, another go-round for all of my friends, another non-stop, will it ever end?",
    "we're never coming back down, yeah, we're looking down on the clouds",
    "watching you get dressed messes with my head, take that bag off your shoulder",
    "come get back in bed, we still got time left, this don't have to be over",
    "and you say it's hard to keep a secret, girl, don't leave me all alone in this hotel",
    "and these shades can hide us from the streets, yeah, one weekend i'll promise that i'll never tell",
    "you should probably stay, probably stay a couple more days, come on let me change your ticket home, oh",
    "don't go, it's not the same when you're gone and it's not good to be all alone",
    "don't play innocent, i know what you meant, when you said you'd come over",
    "aren't we way past that, playing hard to get? we did that when we were younger",
    "why don't we take some time? why don't we take just a little more time?",
    "why don't we make it right? girl, i don't wanna say goodbye",
    "tell me you believe in love, it's not an illusion (yeah)",
    "i've been thinking 'bout the nights and the dangerous tricks",
    "people play on the eyes of the innocent, i could turn a lot of hearts into",
    "breaks with smoke and mirrors disappearing right in front of them",
    "but believe me, i'm not trying to deceive you",
    "i promise falling for me, won't be a mistake",
    "no baby, this is not an illusion, i've really got my heart out on my sleeve",
    "oh, baby, this is not an illusion, there's magic between you and me",
    "no baby, this is not an illusion, you really got me lifted off my feet",
    "you don't ever have to worry 'bout me, 'bout how the cards fall, i'm all that you need tonight",
    "i would never turn your heart into broken parts, you don't have to think twice looking in my eyes",
    "you can tie me up in chains, you can throw away the key, but there's no trap doors",
    "once in a lifetime, it's just right, we make no mistakes",
    "not even a landslide or riptide, could take it all away",
    "somehow, it feels like nothing has changed, right now, my heart is beating the same out loud, someone's calling my name",
    "it sounds like you when i close my eyes, all the stars align",
    "and you are by my side, you are by my side",
    "once in a lifetime, it's just right and we are always safe",
    "not even the bad guys in the dark night, could take it all away",
    "na-na, na-na-na-na, na-na-na-na, na-na-na-na-na-na-na-na",
    "when i'm fat and old and my kids think i'm a joke,'cause i move a little slow when i dance",
    "i can count on you after all that we've been through,'cause i know that you'll always understand",
    "i won't act my age, no i won't act my age, no, i'll still feel the same around you, hey (oh)",
    "when i'm fat and old and my kids think i'm a joke,'cause the stories that i told, i tell again and again",
    "i can count on you after all we got up to,'cause i know that you truly understand",
    "when i can hardly walk and my hair is falling out, we'll still stay up 'til morning, we'll throw the after-party, oh yeah, oh yeah",
    "hey angel, do you know the reasons why, we look up to the sky?",
    "hey angel, do you look at us and laugh when we hold on to the past?",
    "oh i wish i could be more like you, do you wish you could be more like me?",
    "hey angel, tell me, do you ever try to come to the other side?",
    "hey angel, tell me, do you ever cry when we waste away our lives?",
    "yeah i see you at the bar, at the edge of my bed, backseat of my car, in the back of my head",
    "i come alive when i hear your voice, it's a beautiful sound, it's a beautiful noise",
    "i've got fire for a heart, i'm not scared of the dark, you've never seen it look so easy",
    "i got a river for a soul and baby, you're a boat, baby, you're my only reason",
    "if i didn't have you, there would be nothing left, the shell of a man that could never be his best",
    "if i didn't have you, i'd never see the sun, you taught me how to be someone, yeah",
    "all my life, you stood by me, when no one else was ever behind me",
    "all these lights, they can't blind me, with your love, nobody can drag me down",
    "nobody, nobody, nobody can drag me down",
    "i got a river for a soul, and baby, you're a boat, baby you're my only reason",
    "i might never be your knight in shinin' armor",
    "i might never be the one you take home to mother",
    "and i might never be the one who brings you flowers, but i can be the one, be the one tonight",
    "when i first saw you from across the room, i could tell that you were curious, oh, yeah",
    "girl, i hope you're sure what you're looking for 'cause i'm not good at making promises",
    "but if you like causing trouble up in hotel rooms and if you like having secret little rendezvous",
    "if you like to do the things you know that we shouldn't do, then baby, i'm perfect",
    "baby, i'm perfect for you",
    "and if you like midnight driving with the windows down, and if you like going places we can't even pronounce",
    "if you like to do whatever you've been dreaming about, then baby, you're perfect",
    "baby, you're perfect, so let's start right now",
    "i might never be the hands you put your heart in or the arms that hold you any time you want them",
    "but that don't mean that we can't live here in the moment, 'cause i can be the one you love from time to time",
    "and if you like cameras flashin' every time we go out, oh, yeah",
    "and if you're looking for someone to write your breakup songs about, baby, i'm perfect",
    "down to earth, keep on falling when i know it hurts",
    "going faster than a million miles an hour, tryna catch my breath some way, somehow",
    "down to earth, it's like i'm frozen but the world still turns",
    "stuck in motion and the wheels keep spinnin' 'round, movin' in reverse with no way out",
    "and now i'm one step closer to being, two steps far from you",
    "when everybody wants you, everybody wants you",
    "how many nights does it take to count the stars? that's the time it would take to fix my heart",
    "oh, baby, i was there for you, all i ever wanted was the truth, yeah, yeah",
    "how many nights have you wished someone would stay? lie awake only hopin' they're okay",
    "i never counted all of mine, if i tried, i know it would feel like infinity",
    "i told her that i loved her, was not sure if she heard, the roof was pretty windy, and she didn't say a word",
    "party dying downstairs, had nothing left to do, just me, her and the moon",
    "I said, 'you're on fire, babe', then down came the lightning on me",
    "love can be frightening for sure",
    "all i know at the end of the day is you want what you want, and you say what you say",
    "and you follow your heart, even though it'll break sometimes",
    "all i know at the end of the day is you love who you love, there ain't no other way",
    "if there's something i've learned from a million mistakes, you're the one that i want at the end of the day",
    "you're the one that i want at the end of the day",
    "she said the night was over, i said it's forever, 20 minutes later, wound up in the hospital",
    "the priest thinks it's the devil, my mum thinks it's the flu, but, girl, it's only you",
    "when the sun goes down, i know that you and me, and everything will be alright",
    "and when the city's sleeping, you and i can stay awake and keep on dreaming",
    "if i could fly, i'd be comin' right back home to you",
    "i think i might give up everything, just ask me to",
    "pay attention, i hope that you listen 'cause i let my guard down",
    "right now i'm completely defenseless",
    "for your eyes only, i'll show you my heart",
    "for when you're lonely and forget who you are, i'm missing half of me",
    "when we're apart, now you know me for your eyes only",
    "i've got scars even though they can't always be seen",
    "and pain gets hard, but now you're here and i don't feel a thing",
    "i can feel your heart inside of mine, i feel it, i feel it",
    "we made a fire, went down in the flames",
    "we sailed an ocean and drowned in the wave",
    "built a cathedral, but we never prayed",
    "we had it all, yeah and we walked away",
    "point of no returning, now it's just too late to turn around",
    "i try to forgive you, but i struggle 'cause i don't know how",
    "we built it up so high and now i'm falling",
    "it's a long way down from here",
    "we had a mountain but took it for granted",
    "we had a spaceship but we couldn't land it",
    "we found an island, but we got stranded",
    "we had it all, yeah, who could've planned it?",
    "wanna pull an all nighter and get into something we'll never forget",
    "wanna stay up and party the weekend away and not know when to quit",
    "wanna drive in the night till the end of the earth and go over the edge",
    "wanna wake up with you and say baby let's do it all over again",
    "lips so good i forget my name, i swear i could give you everything",
    "i don't need my love, you can take it, you can take it, take it",
    "i don't need my heart, you can break it, you can break it, break it",
    "i just can't get too much of you, baby, it's never, it's never enough",
    "too much is never enough, too much is never enough",
    "remember the day when we've given up, when you told me i didn't give you enough",
    "and all of your friends were saying i'll be leaving you, she's lying in bed with my t-shirt on",
    "just thinking how i went about it wrong, this isn't the stain of a red wine, i'm bleeding love",
    "please believe me, don't you see, the things you mean to me?",
    "oh, i love you, i love you, i love, i love, i love Olivia",
    "i live for you, i long for you, Olivia",
    "i've been idolizing the light in your eyes, Olivia, i live for you, i long for you, Olivia, don't let me go",
    "say what you're feeling and say it now, 'cause i got the feeling you're walking out",
    "and time is irrelevant when i've not been seeing you, the consequences are falling now",
    "there's something i'm having nightmares about and these are the reasons i'm crying out to be with you",
    "when you go and i'm alone, you live in my imagination",
    "the summertime and butterflies, all belong to your creation",
    "i love you, it's all i do, i love you",
    "through the wire, through the wire, through the wire, i'm watching her dance, dress is catching the light",
    "in her eyes there's no lies, no lies, there's no question, she's not in a disguise",
    "with no way out and a long way down, everybody needs someone around",
    "but i can't hold you too close now, through the wire, through the wire",
    "what a feeling to be right here beside you now",
    "holding you in my arms, when the air ran out and we both started running wild",
    "the sky fell down, but you've got stars, they're in your eyes",
    "and i've got something missing tonight, what a feeling to be a king beside you, somehow",
    "i wish i could be there now",
    "i'm watching you like this, imagining you're mine, it's too late, it's too late, am i too late?",
    "tell me now, am i running out of time?",
    "whatever chains are holding you back, holding you back, don't let 'em tie you down",
    "whatever chains are holding you back, holding you back, tell me you believe in that",
    "it's inevitable everything that's good comes to an end",
    "it's impossible to know if after this we can still be friends, yeah",
    "i know you're saying you don't wanna hurt me, well, maybe you should show a little mercy",
    "the way you look i know you didn't come to apologize",
    "hey, hey, hey, oh, why you're wearing that to walk out of my life?",
    "hey, hey, hey, oh, even though it's over you should stay tonight",
    "hey, hey, hey, if tomorrow you won't be mine",
    "won't you give it to me one last time? oh, baby, let me love you goodbye",
    "unforgettable together held the whole world in our hands",
    "unexplainable the love that only we could understand, yeah",
    "i know there's nothing i can do to change it, but is there something that can be negotiated?",
    "my heart's already breaking, baby, go on, twist the knife",
    "one more taste of your lips just to bring me back, to the places we've been and the nights we've had",
    "because if this is it then at least we could end it right, oh, why you're wearing that to walk out of my life?",
    "i wanna write you a song, one as beautiful as you are sweet",
    "with just a hint of pain, for the feeling that i get when you are gone",
    "i wanna write you a song, i wanna lend you my coat",
    "one that's as soft as your cheek, so when the world is cold",
    "you will have a hiding place you can go, i wanna lend you my coat",
    "ooh, everything i need i get from you, ooh, and giving back is all i wanna do",
    "i wanna build you a boat, one as strong as you are free",
    "so any time you think, that your heart is gonna sink, you know it won't, i wanna build you a boat",
    "i wanna write you a song, one to make your heart remember me",
    "so any time i'm gone, you can listen to my voice and sing along",
    "i wanna write you a song",
    "you gotta help me, i'm losin' my mind, keep gettin' the feeling you wanna leave this all behind",
    "thought we were goin' strong, i thought we were holdin' on, aren't we?",
    "no, they don't teach you this in school, now my heart's breakin' and i don't know what to do",
    "thought we were goin' strong, thought we were holdin' on, aren't we?",
    "you and me got a whole lot of history (oh), we could be the greatest team that the world has ever seen",
    "you and me got a whole lot of history (oh), so don't let it go, we can make some more, we can live forever",
    "all of the rumors, all of the fights, but we always find a way to make it out alive",
    "thought we were goin' strong, thought we were holdin' on, aren't we?",
    "minibars, expensive cars, hotel rooms and new tattoos",
    "the good champagne, and private planes, but they don't mean anything",
    "'cause the truth is out, i realize, that without you here, life is just a lie",
    "this is not the end, this is not the end, we can make it, you know it, you know",
    "so don't let me go, so don't let me go, we can live forever!",
    "saw your body language and i know how you're feeling",
    "you look like the kind of girl that's tired of speaking",
    "standing with somebody but he doesn't know what you like",
    "you caught my attention, you were looking at me first",
    "all that i can see's you waking up in my t-shirt",
    "if you're not hooked on anything right now, i can be your vice",
    "all you need to know is, you can call me, when you're lonely",
    "when you can't sleep, i'll be your temporary fix",
    "you control me, even if it's just tonight",
    "you can call me, when you feel like",
    "i'm your good time, i'll be your temporary fix",
    "you can own me and we'll call this what you like",
    "let me be your good night",
    "the night is on your lips and i feel like i'm locked in",
    "there's a million lights, i don't care if they're watching",
    "your body is saying everything, i don't have to read your mind",
    "feel you on my neck while i'm calling a taxi",
    "climbing over me while i climb in the backseat",
    "now we're taking off, now we're taking it off tonight",
    "we can roll in the darkness, let me touch you where your heart is",
    "and if you're feeling the weakness, well, i told you, baby, that you can call me",
    "i'll be your temporary fix, you can call me",
    "a week ago you said to me, 'do you believe i'll never be too far?'",
    "if you're lost, just look for me, you'll find me in the region of the summer stars",
    "the fact that we can sit right here and say goodbye, means we've already won",
    "a necessity for apologies between you and me, baby, there is none",
    "we had some good times, didn't we? we had some good tricks up our sleeve",
    "goodbyes are bittersweet, but it's not the end",
    "i'll see your face again and you will find me",
    "yeah, you will find me, in places that we've never been",
    "for reasons we don't understand, walking in the wind",
    "yesterday i went out to celebrate the birthday of a friend, but as we raised our glasses up to make a toast, i realised you were missing",
    "and i know we'll be alright, child, just close your eyes and see",
    "and i'll be by your side, any time you're needing me",
    "i hear them calling for you, i feel the waves getting started",
    "it's a rush inside i can't control, your eyes keep pulling me in",
    "i know, i know, i know, your friends all talkin' 'bout me",
    "they say i got no chance at all, your fire is burning deep, in my soul, my soul, my soul",
    "i ain't up for debating, ain't in it for the taking, we got the world shaking",
    "in the middle of the night when the wolves come out, they head straight for your heart, like a bullet in the dark",
    "one by one, i take them down, we can run and hide, ain't goin' down without a fight",
    "i hear them calling for you, in the middle of the night when the wolves come out, they come straight for your heart",
    "i ain't up for debating, ain't in it for the taking, we got the world shaking",
    "i wish it wasn't true, but the whole world's tryin' to get a piece of you",
    "and my heart keeps fighting in this battle of fools, gotta make it through, gotta make it through",
    "won't you stay 'til the a.m.?",
    "all my favourite conversations, always made in the a.m., yeah-yeah",
    "feels like this could be forever tonight, break these clocks forget about time",
    "there could be world war 3 going on outside",
    "you and me were raised in the same part of town, got these scars on the same ground",
    "remember how we used to kick around just wasting time?",
    "'cause we don't know what we're saying, we're just swimming 'round in our glasses",
    "and talking out of our asses, like we're all gonna make it, yeah-yeah",
    "feels like this could be forever right now, don't wanna sleep 'cause we're dreaming out loud",
    "trying to behave but you know that we never learned how",
    "you know, i'm always coming back to this place",
    "you know and i'll say, you know, i'm always gonna look for your face",
    "make a little conversation, so long, i've been waiting to let go of myself and feel alive",
    "so many nights i thought it over, told myself i kinda liked her, but there was something missing in her eyes",
    "i was stumbling, looking in the dark (oh) with an empty heart",
    "but you say, you feel the same, could we ever be enough? (oh) maybe we could be enough",
    "and it's alright, calling out for somebody to hold tonight",
    "when you're lost, i'll find the way and i'll be your light",
    "you'll never feel like you're alone, i'll make this feel like home",
    "so hard that i couldn't take it, wanna wake up, and see your face",
    "and remember how good it was being here last night",
    "still high with a little feeling, i see the smile as it starts to creep in",
    "it was there, i saw it in your eyes",
    "one way or another, i'm gonna find ya, i'm gonna get ya, get ya, get ya, get ya",
    "i'm gonna meet ya, meet ya, meet ya, meet ya, one day, maybe next week",
    "i will drive past your house, and if the lights are all down",
    "i'll see who's around, let's go!",
    "and if the lights are all out, i'll follow your bus downtown, see who's hanging out",
    "i wanna hold you, wanna hold you tight, get teenage kicks right through the night",
    "one way or another, i'm gonna win ya, i'm gonna get ya, get ya, get ya, get ya"
]

# === Post One Lyric ===
def post_lyric():
    try:
        lyric = random.choice(lyrics)
        if len(lyric) <= 280:
            client.create_tweet(text=lyric)
            print("Tweeted:", lyric)
        else:
            print("Skipped (too long):", lyric)
    except Exception as e:
        print("Error while posting lyric:", e)


# === Run it ===
if __name__ == "__main__":
    while True:
        print("Posting a lyric...")
        post_lyric()
        print("Sleeping for 3 hours...\n")
        time.sleep(10800)

