services:
  - type: worker
    name: lyric-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    plan: free
    region: oregon
    envVars:
      - key: CONSUMER_KEY
        sync: false
      - key: CONSUMER_SECRET
        sync: false
      - key: ACCESS_TOKEN
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
